print("====================================")
print("DATA CENTER WATER & HEAT LOOP STATUS")
print("====================================")
print("Water Loop:        GREEN")
print("Cooling Loop:      GREEN")
print("Heat Recovery:     ACTIVE")
print("Thermal Storage:   87%")
print("Pump System:       ONLINE")
print("Sensor Network:    ONLINE")
print("AI Control Center: READY")
print("Digital Twin:      SYNCED")
print("Overall Status:    HEALTHY")
